apiVersion: v1
kind: Service
metadata:
  name: aml-backend-service
  namespace: aml-system
spec:
  selector:
    app: aml-backend
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
